### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Frugghi** [Frugghi/DeepMill#2]
**Da fare:**
- [ ] Migliorare l'euristica
- [x] Da riguardare le funzioni che calcolano i pezzi bloccati e i morris (non vanno bene + exc outOfBound)
- [x] Nella seconda fase ricordarsi di aggiungere l'azione di rimozione di una pedina (nella versione Bitboard) ( es: e5d5b2)
- [ ] Valutare se inserire informazioni ridondanti nello stato
- [x] Controllare il count quando una pedina viene mangiata
- [x] Iterative Deepening
- [x] Controllo di pedine bloccate per goal state
- [ ] Sfruttare il tempo dell'avversario per continuare ad eseguire l'algoritmo di ricerca
- [x] Transposition tables (hashing)
- [ ] Evitare i loop
